[general]
main_script_path = "app.py"

[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1a365d"
backgroundColor = "#e6f7ff"
secondaryBackgroundColor = "#f0f9ff"
textColor = "#1a365d"
